### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mustafa-colakoglu** [bennyn/trading-signals#33]
Hi, a cant see examples of algorithms, how can i use any algorthm?

**Comment by bennyn** [comment]
Hi @mustafa-colakoglu, here is an example how to calculate a [Simple Moving Average (SMA)](https://en.wikipedia.org/wiki/Moving_average#Simple_moving_average) with JavaScript using the "trading-signals" library:

```js
const {SMA} = require('trading-signals');

// Create SMA with a window length of 3
const sma = new SMA(3);

// Add 3 values
sma.update(40);
sma.update(30);
sma.update(20);

// Get the result
console.log(sma.getResult().valueOf()); // Result is "30"
```

If you use TypeScript, you will find an example in the readme: https://github.com/bennyn/trading-signals/tree/v1.0.1#usage

Hope this helps you! Happy coding. 💻
